metricbeat.modules:
  - module: system
    metricsets:
      - cpu
      - load
      - memory
      - network
      - process
      - process_summary
      - core
      - diskio
      - socket
    period: 10s
    processes: ['.*']

output.elasticsearch:
  hosts: ['elasticsearch:9200']